apiVersion: v1
kind: Service
metadata:
  name: {{ include "affine.fullname" . }}
  labels:
    {{- include "affine.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
  selector:
    {{- include "affine.selectorLabels" (dict "ctx" . "component" "server") | nindent 4 }}
